### ISSUE TITLE
load fail with latest pull

### ISSUE THREAD

**Issue by davephillips** [JTriggerFish/TriggerFish-VCV#4] opened 2018-09-21 09:41 UTC
Fedora 23 Linux
Rack 0.6.2b from source

Build proceeds without incident but the plugin fails to load:

[0.123 warn src/plugin.cpp:90] Failed to load library ./plugins/TriggerFish-VCV/plugin.so: ./plugins/TriggerFish-VCV/plugin.so: undefined symbol: _ZN13VdpOscillatorIN3dsp11X4ResamplerINS0_24PolyphaseIIR_X2ResamplerILi2ELi1EEEEELi3EE14maxAngularFreqE

Missing object during link stage ? Please advise, thanks. :)

**Comment by JTriggerFish** [comment] 2018-09-21 14:23
Thanks for reporting, I can reproduce on ubuntu but I'm pretty stumped with that one, especially as it works fine on windows and mac, almost seems like a compiler bug ?
Do you happen to know the last revision that you were able to compile ?

**Comment by davephillips** [comment] 2018-09-21 14:32
Sept 17 commit 7ec613f61d41c144746c901194df256677a283d3 works fine.

**Comment by JTriggerFish** [comment] 2018-09-21 14:40
Ok I've figured it out, seems to be coming from old versions of gcc ( I could reproduce with 5.4 ) not implementing the c++17 standard properly for static constexpr members.
Should be fixed by my latest commit, could you confirm it all works for you now  ? ( I only have a linux virtual box and I can't run Rack on it due to issues with Alsa )

**Comment by davephillips** [comment] 2018-09-21 14:47
Yep, you got it. :) Thanks for the quick fix ! (I'll have to update my system soon.)

**Comment by JTriggerFish** [comment] 2018-09-21 14:50
Awesome, lucky my linux image was also pretty old :)

**Closed as completed by JTriggerFish** 2018-09-21 14:50 UTC
